config/routes.rb
Rails.application.routes.draw do
  root 'trips#index'

  devise_for :users

  resources :trips do
    resources :areas do
      resources :attractions
    end

    resources :trip_rights
  end

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  has_many :areas, dependent: :destroy
  has_many :trip_rights, dependent: :destroy
  validates_with CurrencyCodeValidator

  def total
    Money.new(areas.collect(&:total).sum).exchange_to(currency_code)
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  skip_before_action :authenticate_user!, only: :first_or_new
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @banners = Trip.all.collect { |trip| BannerPresenter.new(trip, current_user.id, show_controls: true) }

  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    raise User::NotAuthorized unless user_can_view_trip?

    @presenter = TripPresenter.new(@trip, current_user)
    @polaroids = @trip.areas.collect { |area| Polaroid::AreaPresenter.new(area, @trip) }

  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
    raise User::NotAuthorized unless user_can_edit_trip?

  end

  # POST /trips
  # POST /trips.json
  def create
    Trip.transaction do
      @trip = Trip.new(trip_params)
      respond_to do |format|
        if @trip.save
          TripRight.create!(user_id: current_user.id, trip_id: @trip.id, permission: :owner)
          format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
          format.json { render :show, status: :created, location: @trip }
        else
          format.html { render :new }
          format.json { render json: @trip.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    raise User::NotAuthorized unless user_can_edit_trip?

    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    raise User::NotAuthorized unless user_can_edit_trip?

    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_trip
    @trip = Trip.find(params[:id])
    @banner = BannerPresenter.new(@trip, current_user)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def trip_params
    params.require(:trip).permit(:name, :banner_image, :start_date, :end_date, :currency_code, :map)
  end

  def user_can_edit_trip?
    current_user.present? && TripRight.user_can_edit?(user_id: current_user.id, trip_id: @trip.id)
  end

  def user_can_view_trip?
    current_user.present? && TripRight.user_can_view?(user_id: current_user.id, trip_id: @trip.id)
  end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= form_for(@trip, html: { class: 'form-horizontal' } ) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group field">
    <%= f.label :name, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group field">
    <%= f.label :banner_image, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :banner_image, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group field">
    <%= f.label :map, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :map, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group field">
    <%= f.label :start_date, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.date_field :start_date, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group field">
    <%= f.label :end_date, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.date_field :end_date, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group field">
    <%= f.label :currency_code, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.select :currency_code,
          options_for_select(Hash[*Money::Currency.all.collect{ |money| [money.name, money.iso_code] }.flatten], @trip.currency_code),
          class: 'form-control'
      %>
    </div>
  </div>

  <div class="form-group actions">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/trips/edit.html.erb
<%= content_for :actions do %>
  <li><%= link_to 'Show', trip_path(@trip.id) %></li>
  <li><%= link_to 'Delete', trip_path(@trip.id), method: :delete, data: { confirm: 'Are you sure?' } %></li>
  <li><%= link_to 'Back', trips_path %></li>
<% end %>

<h1>Editing trip</h1>

<%= render 'form' %>

app/views/trips/index.html.erb
<%= content_for :actions do %>
  <li><%= link_to 'New Trip', new_trip_path %></li>
<% end %>

<div class="container-fluid">

  <div class="row">
    <h1>Listing trips</h1>
  </div>

  <% @banners.each do |banner| %>
    <%= render 'partials/banner', banner: banner %>
  <% end %>
</div>

app/views/trips/new.html.erb
<%= content_for :actions do %>
  <li><%= link_to 'Back', trips_path %></li>
<% end %>

<h1>New trip</h1>

<%= render 'form' %>

app/views/trips/show.html.erb
<%= content_for :actions do %>
  <li><%= link_to 'Share Trip', trip_trip_rights_path(@trip) %></li>
  <li><%= link_to 'Add Area', new_trip_area_path(@trip) %></li>
  <li><%= link_to 'Edit', edit_trip_path(@trip) %></li>
  <li><%= link_to 'Back', trips_path %></li>
<% end %>

<div role="tabpanel">

  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#area-panel" aria-controls="area-panel" role="tab" data-toggle="tab">Areas</a></li>
    <li role="presentation"><a href="#calendar-panel" aria-controls="calendar-panel" role="tab" data-toggle="tab">Calendar</a></li>
    <li role="presentation"><a href="#map-panel" aria-controls="map-panel" role="tab" data-toggle="tab">Map</a></li>
  </ul>

  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="area-panel">
      <% @polaroids.in_groups_of(3, false) do |group| %>
        <div class="row">
          <% group.each do |polaroid| %>
            <%= render 'partials/polaroid', polaroid: polaroid %>
          <% end %>
        </div>
      <% end %>
    </div>
    <div role="tabpanel" class="tab-pane" id="calendar-panel">
      <div class="row">
        <div class="col-md-3 <%= @presenter.area_visibility_class %> ">
          <div>
            <div class="text-center">
              <h3>Areas</h3>
            </div>
            <% @presenter.areas.each do |area| %>
              <div
                  class="area <%= area.proposed_date.present? ? '': 'bg-info' %>"
                  data-id="<%= area.id %>"
                  data-proposed-date="<%= area.proposed_date %>"
                  data-cost="<%= area.total.format %>"
                  data-tour="<%= area.tour %>"
              >
                <%= link_to area.name, trip_area_path(@trip, area) %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="<%= @presenter.calendar_column_class %>">
          <div
              id='calendar'
              data-id="<%= @presenter.id %>"
              data-start-date="<%= @presenter.start_date %>"
              data-editable="true"
          ></div>
        </div>
      </div>
    </div>

    <div role="tabpanel" class="tab-pane" id="map-panel">
      <div class="row">
        <div class="col-md-12">
          <iframe
              src="<%= @presenter.map %>"
              width="100%"
              height="700"
          ></iframe>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12 text-center">
    <h1>
      <strong>Total:</strong>
      <%= @presenter.total %>
    </h1>
  </div>
</div>