config/routes.rb
Rails.application.routes.draw do
  root 'trips#index'

  devise_for :users

  resources :trips do
    resources :areas do
      resources :attractions
    end

    resources :trip_rights
  end

end

app/models/trip_right.rb
class TripRight < ActiveRecord::Base
  validates_inclusion_of :permission, in: [:owner, :collaborator, :viewer], allow_nil: false

  def self.user_can_grant?(user_id: user_id, trip_id: trip_id)
    right = where(user_id: user_id, trip_id: trip_id).first
    right.present? ? right.can_grant? : false
  end

  def self.user_can_edit?(user_id: user_id, trip_id: trip_id)
    right = where(user_id: user_id, trip_id: trip_id).first
    right.present? ? right.can_edit? : false
  end

  def self.user_can_view?(user_id: user_id, trip_id: trip_id)
    right = where(user_id: user_id, trip_id: trip_id).first
    right.present? ? right.can_view? : false
  end

  def permission
    super.to_sym if super.present?
  end

  def permission=(perm)
    super(perm.to_sym)
    permission
  end

  def can_view?
    [:owner, :collaborator, :viewer].include? permission
  end

  def can_edit?
    [:owner, :collaborator].include? permission
  end

  def can_grant?
    [:owner].include? permission
  end
end

app/controllers/trip_rights_controller.rb
class TripRightsController < ApplicationController
  before_action :set_trip_right, only: [:show, :edit, :update, :destroy]
  before_action :set_trip

  respond_to :html

  def index
    @trip_rights = TripRight.where(trip_id: @trip.id).collect{ |right| TripRightPresenter.new(right) }
    @banner = BannerPresenter.new(@trip, current_user)
  end

  def show
    @banner = BannerPresenter.new(@trip, current_user)
  end

  def new
    raise User::NotAuthorized unless user_can_grant_rights?

    @trip_right = TripRight.new(trip_id: @trip.id)
    @form = TripRightForm.new(@trip_right)
    @banner = BannerPresenter.new(@trip, current_user)
  end

  def edit
    raise User::NotAuthorized unless user_can_grant_rights?

    @form = TripRightForm.new(@trip_right)
    @banner = BannerPresenter.new(@trip, current_user)
  end

  def create
    raise User::NotAuthorized unless user_can_grant_rights?

    @trip_right = TripRight.new(trip_right_params.merge(trip_id: @trip.id))
    respond_to do |format|
      begin
        user = User.find(@trip_right.user_id)
        if @trip_right.save
          format.html do
            redirect_to(
              trip_trip_rights_path(@trip),
              notice: "#{user.email} is now a #{@trip_right.permission} of #{@trip.name}."
            )
          end
          format.json { render :show, status: :created, location: trip }
        else
          format.html { render :new }
          format.json { render json: @trip_right.errors, status: :unprocessable_entity }
        end
      rescue ActiveRecord::RecordNotUnique => exception
        format.html do
          redirect_to(
            new_trip_trip_right_path(@trip),
            alert: "#{user.email} is already a #{@trip_right.permission} of #{@trip.name}.",
          )
        end
      end
    end
  end

  def update
    raise User::NotAuthorized unless user_can_grant_rights?

    @trip_right.update(trip_right_params)
    respond_with(@trip, @trip_right)
  end

  def destroy
    raise User::NotAuthorized unless user_can_grant_rights?

    if @trip_right.permission == :owner
        redirect_to(
          trip_trip_rights_path(@trip),
          alert: "This guy owns the trip, McNugget",
        ) and return
    else
      @trip_right.destroy
      respond_with(@trip, @trip_right)
    end
  end

private

  # Use callbacks to share common setup or constraints between actions.
  def set_trip
    @trip = Trip.find(params[:trip_id])
  end

  def set_trip_right
    @trip_right = TripRight.find(params[:id])
  end

  def trip_right_params
    params.require(:trip_right).permit(:trip_id, :user_id, :permission)
  end

  def user_can_grant_rights?
    current_user.present? && TripRight.user_can_view?(user_id: current_user.id, trip_id: @trip.id)
  end

end

app/helpers/trip_rights_helper.rb
module TripRightsHelper
end

app/views/trip_rights/_form.html.erb
<%= form_for([@trip, @trip_right], html: { class: 'form-horizontal' } ) do |f| %>
  <% if @trip_right.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip_right.errors.count, "error") %> prohibited this trip_right from being saved:</h2>

      <ul>
      <% @form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group field">
    <%= f.label :user_id, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.select :user_id,
            options_for_select(@form.users, @form.user_id),
            class: 'form-control'
      %>
    </div>
  </div>

  <div class="form-group field">
    <%= f.label :permission, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.select :permission,
            options_for_select(@form.permissions, @form.permission),
            class: 'form-control'
      %>
    </div>
  </div>

  <div class="form-group actions">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/trip_rights/edit.html.erb
<%= content_for :actions do %>
  <li><%= link_to 'Show', trip_trip_rights_path(@trip.id, @trip_right.id) %></li>
  <li><%= link_to 'Delete', trip_trip_right_path(@trip.id, @trip_right.id), method: :delete, data: { confirm: 'Are you sure?' } %></li>
  <li><%= link_to 'Back', trip_trip_rights_path %></li>
<% end %>
<h1>Editing permission</h1>

<%= render 'form' %>

app/views/trip_rights/index.html.erb
<%= content_for :actions do %>
  <li><%= link_to 'New permission', new_trip_trip_right_path %></li>
  <li><%= link_to 'Back', trip_path(@trip.id) %></li>
<% end %>

<h1>Listing permissions</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>User</th>
      <th>Permission</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @trip_rights.each do |trip_right| %>
      <tr>
        <td class="clickable-cell" data-url="<%= trip_right.view_path %>"><%= link_to trip_right.user_email, trip_right.view_path %></td>
        <td class="clickable-cell" data-url="<%= trip_right.view_path %>"><%= link_to trip_right.permission, trip_right.view_path %></td>
        <td><%= link_to 'Edit', trip_right.edit_path %></td>
        <td><%= link_to 'Destroy', trip_right.view_path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/trip_rights/new.html.erb
<%= content_for :actions do %>
  <li><%= link_to 'Back', trip_trip_rights_path %></li>
<% end %>

<h1>New permission</h1>

<%= render 'form' %>

app/views/trip_rights/show.html.erb
<%= content_for :actions do %>
  <li><%= link_to 'Edit', edit_trip_trip_right_path(@trip.id, @trip_right.id) %></li>
  <li><%= link_to 'Back', trip_trip_rights_path(@trip.id) %></li>
<% end %>

<p>
  <strong>Trip Id:</strong>
  <%= @trip_right.trip_id %>
</p>

<p>
  <strong>User Id:</strong>
  <%= @trip_right.user_id %>
</p>

<p>
  <strong>Permission:</strong>
  <%= @trip_right.permission %>
</p>

<%= link_to 'Edit', edit_trip_trip_right_path(@trip.id, @trip_right.id) %> |
<%= link_to 'Back', trip_trip_rights_path(@trip.id) %>