config/routes.rb
Rails.application.routes.draw do
  root 'trips#index'

  devise_for :users

  resources :trips do
    resources :areas do
      resources :attractions
    end

    resources :trip_rights
  end

end

app/models/area.rb
class Area < ActiveRecord::Base
  has_many :attractions, dependent: :destroy
  validates_with CurrencyCodeValidator

  def total
    Money.new(attractions.collect(&:cost).sum).exchange_to(currency_code)
  end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]
  before_action :set_trip

  # GET /areas
  # GET /areas.json
  def index
    raise User::NotAuthorized unless user_can_view_area?

    @areas = @trip.areas.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
    raise User::NotAuthorized unless user_can_view_area?

    @presenter = AreaPresenter.new(@area)
    @polaroids = @area.attractions.collect { |attraction| Polaroid::AttractionPresenter.new(attraction, @area, @trip) }
  end

  # GET /areas/new
  def new
    raise User::NotAuthorized unless user_can_edit_area?

    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
    raise User::NotAuthorized unless user_can_edit_area?
  end

  # POST /areas
  # POST /areas.json
  def create
    raise User::NotAuthorized unless user_can_edit_area?

    @area = Area.new(area_params.merge(trip_id: @trip.id))

    respond_to do |format|
      if @area.save
        format.html { redirect_to [@trip, @area], notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: [@trip, @area] }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    raise User::NotAuthorized unless user_can_edit_area?

    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to [@trip, @area], notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: [@trip, @area] }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    raise User::NotAuthorized unless user_can_edit_area?

    @area.destroy
    respond_to do |format|
      format.html { redirect_to trip_path(@trip), notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private

  # Use callbacks to share common setup or constraints between actions.
  def set_trip
    @trip = Trip.find(params[:trip_id])
    @banner = BannerPresenter.new(@trip, current_user)
  end

  def set_area
    @area = Area.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def area_params
    params.
      require(:area).
      permit(:trip_id, :name, :description, :image, :proposed_date, :tour, :currency_code)
  end

  def user_can_edit_area?
    current_user.present? && TripRight.user_can_edit?(user_id: current_user.id, trip_id: @trip.id)
  end

  def user_can_view_area?
    current_user.present? && TripRight.user_can_view?(user_id: current_user.id, trip_id: @trip.id)
  end

end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.erb
<%= form_for([@trip, @area], html: { class: 'form-horizontal' } ) do |f| %>
  <% if @area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% @area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group field">
    <%= f.label :name, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group field">
    <%= f.label :description, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: 'form-control', rows: 10 %>
    </div>
  </div>

  <div class="form-group field">
    <%= f.label :image, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :image, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group field">
    <%= f.label :proposed_date, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.date_field :proposed_date, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group field">
    <%= f.label :tour, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.number_field :tour, in: 0..4, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group field">
    <%= f.label :currency_code, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.select :currency_code,
          options_for_select(Hash[*Money::Currency.all.collect{ |money| [money.name, money.iso_code] }.flatten], @area.currency_code),
          class: 'form-control'
      %>
    </div>
  </div>

  <div class="form-group actions">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/areas/edit.html.erb
<%= content_for :actions do %>
  <li><%= link_to 'Show', trip_areas_path(@trip.id, @area.id) %></li>
  <li><%= link_to 'Delete', trip_area_path(@trip.id, @area.id), method: :delete, data: { confirm: 'Are you sure?' } %></li>
  <li><%= link_to 'Back', trip_path(@trip.id) %></li>
<% end %>

<h1>Editing area</h1>

<%= render 'form' %>

app/views/areas/index.html.erb
<%= content_for :actions do %>
  <li><%= link_to 'New Area', new_trip_area_path(@trip.id) %></li>
<% end %>

<h1>Listing areas</h1>

<table>
  <thead>
    <tr>
      <th>Trip</th>
      <th>Name</th>
      <th>Description</th>
      <th>Cost</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= area.trip %></td>
        <td><%= area.name %></td>
        <td><%= area.description %></td>
        <td><%= area.cost %></td>
        <td><%= area.image %></td>
        <td><%= link_to 'Show', trip_area_path(@trip.id, area.id) %></td>
        <td><%= link_to 'Edit', edit_trip_area_path(@trip.id, area.id) %></td>
        <td><%= link_to 'Destroy', [@trip.id, area.id], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/areas/new.html.erb
<%= content_for :actions do %>
  <li><%= link_to 'Back', trip_path(@trip.id) %></li>
<% end %>

<h1>New area</h1>

<%= render 'form' %>

app/views/areas/show.html.erb
<%= content_for :actions do %>
  <li><%= link_to 'Add Attraction', new_trip_area_attraction_path(@trip.id, @area.id) %></li>
  <li><%= link_to 'Edit', edit_trip_area_path(@trip.id, @area.id) %></li>
  <li><%= link_to 'Back', trip_path(@trip.id) %></li>
<% end %>

<div class="row">
  <div class="col-md-12 text-center">
    <h3><%= @presenter.name %> <small><%= @presenter.proposed_date %></small></h3>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="row thumbnail area-thumbnail">
      <div class="col-md-6">
        <%= image_tag @presenter.image, class: 'area-image' %>
      </div>
      <div class="col-md-6">
        <blockquote class="text-left">
          <p>
            <%= @presenter.description %>
          </p>

          <footer>
            <strong>Total:</strong>
            <%= @presenter.total %>
          </footer>
        </blockquote>
      </div>
    </div>
  </div>
</div>

<% @polaroids.in_groups_of(3, false) do |group| %>
  <div class="row">
    <% group.each do |polaroid| %>
      <%= render 'partials/polaroid', polaroid: polaroid %>
    <% end %>
  </div>
<% end %>