config/routes.rb
Rails.application.routes.draw do
  root 'trips#index'

  devise_for :users

  resources :trips do
    resources :areas do
      resources :attractions
    end

    resources :trip_rights
  end

end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  before_action :set_attraction, only: [:show, :edit, :update, :destroy]
  before_action :set_area
  before_action :set_trip

  # GET /attractions
  # GET /attractions.json
  def index
    raise User::NotAuthorized unless user_can_view_attraction?

    @attractions = @area.attractions.all
    @banner = BannerPresenter.new(@trip, current_user)
  end

  # GET /attractions/1
  # GET /attractions/1.json
  def show
    raise User::NotAuthorized unless user_can_view_attraction?

    @banner = BannerPresenter.new(@trip, current_user)
    @polaroid = Polaroid::AttractionPresenter.new(@attraction, @area, @trip, full_width: true)
  end

  # GET /attractions/new
  def new
    raise User::NotAuthorized unless user_can_edit_attraction?

    @attraction = Attraction.new(area: @area)
    @banner = BannerPresenter.new(@trip, current_user)
  end

  # GET /attractions/1/edit
  def edit
    raise User::NotAuthorized unless user_can_edit_attraction?

    @banner = BannerPresenter.new(@trip, current_user)
  end

  # POST /attractions
  # POST /attractions.json
  def create
    raise User::NotAuthorized unless user_can_edit_attraction?

    @attraction = @area.attractions.new({area: @area}.merge(attraction_params))

    respond_to do |format|
      if @attraction.save
        format.html { redirect_to [@trip, @area, @attraction], notice: 'Attraction was successfully created.' }
        format.json { render :show, status: :created, location: @attraction }
      else
        format.html { render :new }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attractions/1
  # PATCH/PUT /attractions/1.json
  def update
    raise User::NotAuthorized unless user_can_edit_attraction?

    respond_to do |format|
      if @attraction.update(attraction_params)
        format.html { redirect_to [@trip, @area, @attraction], notice: 'Attraction was successfully updated.' }
        format.json { render :show, status: :ok, location: @attraction }
      else
        format.html { render :edit }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attractions/1
  # DELETE /attractions/1.json
  def destroy
    raise User::NotAuthorized unless user_can_edit_attraction?

    @attraction.destroy
    respond_to do |format|
      format.html { redirect_to trip_area_path(@trip, @area), notice: 'Attraction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private

  # Use callbacks to share common setup or constraints between actions.
  def set_attraction
    @attraction = Attraction.find(params[:id])
  end

  def set_area
    @area = Area.find(params[:area_id])
  end

  def set_trip
    @trip = Trip.find(params[:trip_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def attraction_params
    params.
      require(:attraction).
      permit(:area_id, :name, :description, :cost, :image, :link).
      tap do |params|
        params[:cost] = BigDecimal.new(params[:cost])
      end
  end

  def user_can_edit_attraction?
    current_user.present? && TripRight.user_can_edit?(user_id: current_user.id, trip_id: @trip.id)
  end

  def user_can_view_attraction?
    current_user.present? && TripRight.user_can_view?(user_id: current_user.id, trip_id: @trip.id)
  end

end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/views/attractions/_form.html.erb
<%= form_for([@trip, @area, @attraction], html: { class: 'form-horizontal' } ) do |f| %>
  <% if @attraction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attraction.errors.count, "error") %> prohibited this attraction from being saved:</h2>

      <ul>
      <% @attraction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group field">
    <%= f.label :name, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group field">
    <%= f.label :description, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: 'form-control', rows: 10 %>
    </div>
  </div>

  <div class="form-group field">
    <%= f.label :cost, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.number_field :cost,
            value: number_with_precision(@attraction.cost, precision: 2),
            step: 'any',
            class: 'form-control'
      %>
    </div>
  </div>

  <div class="form-group field">
    <%= f.label :image, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :image, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group field">
    <%= f.label :link, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :link, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group actions">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/attractions/edit.html.erb
<%= content_for :actions do %>
  <li><%= link_to 'Show', trip_area_attractions_path(@trip.id, @area.id, @attraction.id) %></li>
  <li><%= link_to 'Delete', trip_area_attraction_path(@trip.id, @area.id, @attraction.id), method: :delete, data: { confirm: 'Are you sure?' } %></li>
  <li><%= link_to 'Back', trip_area_path(@trip.id, @area.id) %></li>
<% end %>

<h1>Editing attraction</h1>

<%= render 'form' %>

app/views/attractions/index.html.erb
<%= content_for :actions do %>
  <li><%= link_to 'New Attraction', new_trip_area_attraction_path(@trip.id, @area.id) %></li>
<% end %>

<h1>Listing attractions</h1>

<table>
  <thead>
    <tr>
      <th>Area</th>
      <th>Name</th>
      <th>Description</th>
      <th>Cost</th>
      <th>Image</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attractions.each do |attraction| %>
      <tr>
        <td><%= attraction.area %></td>
        <td><%= attraction.name %></td>
        <td><%= attraction.description %></td>
        <td><%= attraction.cost %></td>
        <td><%= attraction.image %></td>
        <td><%= attraction.link %></td>
        <td><%= link_to 'Show', trip_area_attraction_path(@trip.id, @area.id, attraction.id) %></td>
        <td><%= link_to 'Edit', edit_trip_area_attraction_path(@trip.id, @area.id, attraction.id) %></td>
        <td><%= link_to 'Destroy', [@trip.id, @area.id, attraction.id], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/attractions/new.html.erb
<%= content_for :actions do %>
  <li><%= link_to 'Back', trip_area_path(@trip.id, @area.id) %></li>
<% end %>

<h1>New attraction</h1>

<%= render 'form' %>

app/views/attractions/show.html.erb
<%= content_for :actions do %>
  <li><%= link_to 'Add Attraction', new_trip_area_attraction_path(@trip.id, @area.id) %></li>
  <li><%= link_to 'Edit', edit_trip_area_attraction_path(@trip.id, @area.id, @attraction.id) %></li>
  <li><%= link_to 'Back', trip_area_path(@trip.id, @area.id) %></li>
<% end %>

<div class="row">
  <%= render 'partials/polaroid', polaroid: @polaroid %>
</div>

</div>